### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by jfslater98** [wilcoverhoeven/pico-images-plugin#1]
Sorry to bother you, but couldn't google a solution. When I put pico_images.php in the themes directory, my web site gets pushed to https://github.com/wilcoverhoeven/pico-images-plugin/blob/master/pico_images.php

When I delete that file I go to http://dev.hackslashchop.com (the proper URL). I believe I've followed your instructions correctly, but clearly I've done something wrong. It's my first Pico site, so my apologies for the ignorant question. I couldn't find any forums on Pico basics, so I'm a bit lost. Thanks for your patience.

John

**Comment by wilcoverhoeven** [comment]
@jfslater98 Hi John, did you try putting the pico_images.php file inside the **plugins** folder?

**Comment by jfslater98** [comment]
Yes, I did. That seems to cause the trouble. When it's in the Plugins folder, the site seems to redirect. I just put it in now, to make sure I didn't miss something. See attached screen capture, and visit http://dev.hackslashchop.com to confirm. I have to run off to work now, but can follow up later. Really appreciate you getting back to me!!
![in_plugins](https://cloud.githubusercontent.com/assets/22016019/18271942/f56af956-7402-11e6-8ec5-d785a589cafd.jpg)

**Comment by wilcoverhoeven** [comment]
Did you by any change download the pico_images.php file by right clicking and selecting "save link as"?
<img width="557" alt="screen shot 2016-09-06 at 13 49 12" src="https://cloud.githubusercontent.com/assets/12970892/18272645/1d22678c-7439-11e6-822b-574bbc3248a5.png">

If so, please download the file again from the "releases" or use the "clone or download" button. "save link as" will not work, it saves the github page and not the file.
<img width="1006" alt="screen shot 2016-09-06 at 13 49 35" src="https://cloud.githubusercontent.com/assets/12970892/18272718/abf2a8fa-7439-11e6-9fea-077b04a7ebb0.png">

**Comment by jfslater98** [comment]
Ah, that's exactly what I did. I just used the "clone or download" feature, and now my site comes up. It's not working the way I expect, but that's likely due to my overall ignorance of how Pico works, so I have more work to do. Sorry for the stupid question. Really appreciate your help and patience, thank you very much!!

**Comment by wilcoverhoeven** [comment]
No problem, I'm glad I could help.
