### ISSUE TITLE
Fixing .htaccess to make this plugin working

### ISSUE THREAD

**Issue by nimah79** [wilcoverhoeven/pico-images-plugin#2]
This plugin won't work because of .htaccess file of Pico.

You should change content of .htaccess from:
`RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?$1 [L,QSA]
RewriteRule ^(\.git|config|content|lib|vendor)(/.*)?$ index.php?$0 [L,QSA]
RewriteRule ^(CHANGELOG\.md|composer\.(json|lock)) index.php?404 [L]
<IfModule mod_env.c>
    SetEnv PICO_URL_REWRITING 1
</IfModule>
Options -Indexes -MultiViews`

To:
`RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?$1 [L,QSA]
RewriteRule ^(\.git|config|content|lib|vendor)(/.*.md)?$ index.php?$0 [L,QSA]
RewriteRule ^(CHANGELOG\.md|composer\.(json|lock)) index.php?404 [L]
<IfModule mod_env.c>
    SetEnv PICO_URL_REWRITING 1
</IfModule>
Options -Indexes -MultiViews`

**Comment by wilcoverhoeven** [comment]
Yes, you are right. I did something similar myself. I'll add it to the Install section of the readme.
